{% set name = "mne-realtime" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8d930ff20b23e5c34fd23e8ec54f435b17ecfb2aa27f765b42d8e249b93b0fd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - mne-base

test:
  imports:
    - mne_realtime
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mne.tools/mne-realtime
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - mne_realtime/externals/LICENSE_BSD
  summary: 'Realtime data analysis with MNE-Python'
  dev_url: https://github.com/mne-tools/mne-realtime

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
